@startuml ユースケース図
' left to right direction
actor 出荷担当者#DDDDDD;line:black;line.bold;
actor 社員#DDDDDD;line:black;line.bold;
rectangle 販売管理システム {
usecase 注文商品を確認する
usecase 出荷状況を登録する
usecase 社員情報を参照する
}
出荷担当者-->注文商品を確認する
出荷担当者-->出荷状況を登録する
社員-->社員情報を参照する
@enduml